Content/Qc.QcProjectSdk.Sample/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace Qc.QcProjectSdk.Sample.Pages
{
  public class IndexModel : PageModel
  {
    private readonly QcProjectService _service;
    public IndexModel(QcProjectService service)
    {
        _service = service;
    }
    public IActionResult OnPostGetTest()
    {
      return new JsonResult(new { msg = "ok" }, new JsonSerializerSettings() { Formatting = Formatting.Indented });
    }
  }
}

Content/Qc.QcProjectSdk.Sample/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "测试";
}
<form method="post">
    <button asp-page-handler="GetTest">测试</button>
</form>

Content/Qc.QcProjectSdk.Sample/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] (ProjectName) Sdk示例</title>

    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="container">
        <fieldset>
            <legend>(ProjectName) Sdk接口列表</legend>
            <ul>
              
            </ul>
        </fieldset>
        <div>
            <fieldset>
                <legend>@ViewData["Title"]</legend>
                @RenderBody()
            </fieldset>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>